version: '3'
services:

  mongo:
    image: mongo:4.0.5-xenial
    volumes:
      - ${MONGO_DATA_DIR}:/data/db
      - ./docker-config/mongo/:/config/dbs/
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
      NODE_ENV: ${NODE_ENV}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}

  node:
    build:
      context: .
      dockerfile: ./Dockerfiles/node/Dockerfile
    user: node
    env_file:
      - ./.env
    expose:
      - "${PORT}"
    depends_on:
      - mongo
      - redis
    command: "npm start"

  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - mongo