version: '3'
services:

# The development configuration lives here
  mongo:
    ports:
      - ${ME_CONFIG_MONGODB_PORT}:${DB_PORT}
    environment:
      DB_TEST_NAME: ${DB_TEST_NAME}
      DB_TEST_PASSWORD: ${DB_TEST_PASSWORD}
      DB_TEST_USER: ${DB_TEST_USER}

  mongo-express:
  # TODO: Check if a contribution is needed here
  # https://github.com/mongo-express/mongo-express-docker/pull/65/files
  # In order to see if we can use the latest container image
  # of mongo-express without the need of the mongo string url necessarily
  # and also have the alternative to be able to use the port as a separate
  # variable
    image: mongo-express:0.54
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ADMIN_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_PORT: ${ME_CONFIG_MONGODB_PORT}
    depends_on:
      - mongo
    ports:
      - ${MONGO_EXPRESS_EXTERNAL_PORT}:8081
    expose:
      - "${MONGO_EXPRESS_EXTERNAL_PORT}"

  node:
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    ports:
      - ${PORT}:${PORT}
      - ${DEBUG_NODE_PORT}:${DEBUG_NODE_PORT}
    environment:
      DEBUG_NODE_SERVER: ${DEBUG_NODE_SERVER}
      DEBUG_NODE_PORT: ${DEBUG_NODE_PORT}

  redis:
    ports:
      - ${REDIS_EXTERNAL_PORT}:${REDIS_PORT}
