version: '3'
services:

  mongo:
    image: mongo:4.0.5-xenial
    restart: always
    volumes:
      - ~/docker-mongo/data:/data/db
    env_file:
      - ./.env-mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    env_file:
      - ./.env-mongo-express
