version: '3'
services:

  mongo:
    build:
      context: .
      dockerfile: Dockerfiles/mongo.yml
    restart: always
    volumes:
      - ~/docker-mongo/data:/data/db
      - ./docker-config/mongo/:/test-config
    env_file:
      - ./.env
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD}
      NODE_ENV: ${NODE_ENV}
      DB_NAME: ${DB_NAME}
      DB_TEST_NAME: ${DB_TEST_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_TEST_PASSWORD: ${DB_TEST_PASSWORD}
      DB_USER: ${DB_USER}
      DB_TEST_USER: ${DB_TEST_USER}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./.env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ADMIN_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ADMIN_PASSWORD}

  node:
    image: node:8.15.0-jessie
    user: node
    working_dir: /home/node/app
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/home/node/app
    environment:
      NODE_ENV: ${NODE_ENV}
    expose:
      - "${PORT}"
    command: "npm start"
